title: sgID
description: >- # this means to ignore newlines until "baseurl:"
  Sign in with sgID
tagline: >-
  Designed for Privacy
baseurl: "/" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
